site_name: Micro Simulations for Education
site_description: 'Resources for teaching classes with Micro Simulators.'
site_author: 'UMN Students'
repo_name: 'ee-microsims'
site_url: 'https://kenn0727.github.io/ee-microsims'
repo_url: 'https://github.com/kenn0727/ee-microsims'

nav:
  - Gallery: index.md
  - Simulations:
    - Default: sims/index.md
    - Vector Sim: sims/linear-algebra-sim/index.md
    - Mobius Transform: sims/mobius-transform/index.md
    - Frequency Detection: sims/frequency-detection/index.md
    - LC Oscillator: sims/lc-oscillator/index.md
    - RC Lowpass Filter: sims/rc-lowpass-filter/index.md
    - Analog Mod: sims/analog-mod/index.md
    - Mosfet Biasing: sims/mosfet-biasing/index.md
    - Buck Converter: sims/buck-converter/index.md
    - FFT: sims/fft/index.md
    - Shift and Scale: sims/shift&scale/index.md
    - Noise Modification: sims/noise-modification/index.md
  - License: license.md

edit_uri: 'blob/master/docs'

theme:
  name: material
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
