site_name: Micro Simulations for Education
site_description: 'Resources for teaching classes with Micro Simulators.'
site_author: 'UMN Students of Group 6'
repo_name: 'Group6_Microsims'
site_url: 'https://kenn0727.github.io/Group6_Microsims'
repo_url: 'https://github.com/kenn0727/Group6_Microsims'

nav:
  - Gallery: index.md
  - Simulations:
    - Default: sims/index.md
    - Vector Sim: sims/Linear-Algebra-Sim/index.md
    - Mobius Transform: sims/Mobius-Transform/index.md
  - License: license.md

edit_uri: 'blob/master/docs'

theme:
  name: material
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true